title: Ernährung
author: Raspberry
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Er lernt ihr, was gute Ernährung ausmacht!
theme: minima

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage
